redis:
  hostname: localhost
  port: 6379

spring:
  application:
    name: ceres-routing-service

influxdb.enterprise.url: http://localhost:8086
is.using.influxdb.enterprise: true
---
spring:
  profiles: development

server.port: 8081

redis:
  hostname: localhost
  port: 6379

influxdb.scaler.url: http://localhost:8083
influxdb.enterprise.url: http://localhost:8086

rest-template:
  request-config:
    connection-request-timeout: 120000  # timeout when requesting a connection from the connection manager
    connect-timeout: 120000             # timeout until a connection is established
    socket-timeout: 120000              # timeout for waiting for data

  pooling-http-client-connection-manager:
    max-total: 5 # Max number of connection to pool

management:
  endpoints:
    web:
      exposure:
        include: "health,jolokia,metrics"
  metrics:
    tags:
      stack: "dev"
      service: "routing-service"
    export:
      influx:
        db: ceres
        uri: http://localhost:8086
        auto-create-db: true
---
spring:
  profiles: production

redis:
  hostname: ${REDIS_HOSTNAME}
  port: ${REDIS_PORT}

influxdb.scaler.url: ${INFLUXDB_SCALER_URL}
influxdb.enterprise.url: ${INFLUXDB_ENTERPRISE_URL}
is.using.influxdb.enterprise: ${IS_USING_INFLUXDB_ENTERPRISE}

rest-template:
  request-config:
    connection-request-timeout: 120000  # timeout when requesting a connection from the connection manager
    connect-timeout: 120000             # timeout until a connection is established
    socket-timeout: 120000              # timeout for waiting for data

  pooling-http-client-connection-manager:
    max-total: 5 # Max number of connection to pool

management:
  endpoints:
    web:
      exposure:
        include: "health,jolokia,metrics"
  metrics:
    tags:
      stack: "prod"
      service: "routing-service"
    export:
      influx:
        db: ceres
        uri: ${INFLUXDB_METRICS_URL}
        auto-create-db: true